/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  // "guides": 
  // [
  //   "guides/install",
  //   "guides/prepare",
  //   "guides/start-to-use",
  //   "guides/what-happened",
  //   "guides/message-chain",
  //   "guides/use-filter",
  //   "guides/add-scheduled-job"
  // ],

  // "api":
  // [
  //   "api/install"
  // ],

  "guides":
  [
    {
      type: "autogenerated",
      dirName: "guides"
    }
  ],

  "api":
  [
    {
      type: "autogenerated",
      dirName: "api"
    }
  ],
};
